FROM python:3.13-alpine
RUN apk add --no-cache gcc musl-dev libsecp256k1-dev
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
COPY pyproject.toml uv.lock ./
ENV PATH="/app/.venv/bin:$PATH"
RUN uv sync --frozen --no-install-project --no-default-groups --group proxy
COPY browser-server/webs.py ./

ENTRYPOINT ["python"]
CMD ["webs.py"]
