services:
  browser:
    image: mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble
    entrypoint: [ "/bin/sh" ]
    command: [ "-c", "sed 's|$${BROWSER_PORT}|${BROWSER_PORT}|g' /app/browser-launch-params.json > /tmp/launch-params.json && npx -y playwright@${PLAYWRIGHT_VERSION} launch-server --browser=chromium --config /tmp/launch-params.json" ]
#    user: $(id -u):$(id -g)
#    network_mode: host
    init: true
    stdin_open: true
    tty: true
    environment:
      XDG_RUNTIME_DIR: /tmp
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
    volumes:
      - ./browser-launch-params.json:/app/browser-launch-params.json
      - ./browser-local-storage/:/app/browser-local-storage
      - ./browser-downloads/:/app/browser-downloads
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/user/$(id -u)/$WAYLAND_DISPLAY:/run/user/$(id -u)/$WAYLAND_DISPLAY
    devices:
      - /dev/dri:/dev/dri
    expose:
      - "${BROWSER_PORT}"
  proxy:
    image: mitmproxy/mitmproxy:${MITM_VERSION}
    entrypoint: [ "/app/entry.sh" ]
    command: [ "-s", "/app/webs.py", "--listen-port", "8080", "--mode", "reverse:http://browser:${BROWSER_PORT}"]
    init: true
    stdin_open: true
    tty: true
#    network_mode: host
    volumes:
      - ./entry.sh:/app/entry.sh
      - ./webs.py:/app/webs.py
    ports:
      - "${PROXY_PUBLIC_PORT}:8080"
    depends_on:
      - browser