FROM python:3.13-alpine
RUN apk add --no-cache gcc musl-dev libsecp256k1-dev
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --no-default --group proxy
COPY browser-server/webs.py ./
CMD ["python", "webs.py"]
