services:
  browser-headed:
    restart: always
    image: mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble
    entrypoint: [ "/bin/sh" ]
    command: [ "-c", "sed 's|$${BROWSER_PORT}|${BROWSER_PORT}|g' /app/browser-launch-params.json > /tmp/launch-params.json && npx -y playwright@${PLAYWRIGHT_VERSION} launch-server --browser=chromium --config /tmp/launch-params.json" ]
    init: true
    stdin_open: true
    tty: true
    environment:
      XDG_RUNTIME_DIR: /tmp
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
    volumes:
      - ./browser-launch-params.json:/app/browser-launch-params.json:ro
      - ./browser-local-storage/:/app/browser-local-storage
      - ./browser-downloads/:/app/browser-downloads
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/user/$(id -u)/$WAYLAND_DISPLAY:/run/user/$(id -u)/$WAYLAND_DISPLAY
    devices:
      - /dev/dri:/dev/dri
    networks:
      - secure_net
    expose:
      - "${BROWSER_PORT}"

  proxy-headed:
    restart: always
    image: python:3.13-alpine
    entrypoint: [ "/app/entry.sh" ]
    command: [ "/app/webs.py" ]
    tty: true
    init: true
    stdin_open: true
    volumes:
      - ./entry.sh:/app/entry.sh:ro
      - ./webs.py:/app/webs.py:ro
    ports:
      - "${PROXY_PUBLIC_PORT}:8080"
    environment:
      BROWSER_URL: ws://browser-headed:${BROWSER_PORT}/srv
    networks:
      - secure_net

  browser-manual:
    image: mcr.microsoft.com/playwright/python:v1.54.0-noble
    entrypoint: [ "/bin/sh" ]
    command: [ "-c", "pip install --root-user-action=ignore --disable-pip-version-check -q playwright==${PLAYWRIGHT_VERSION} && exec xvfb-run --error-file=/app/browser-downloads/xvfb.log python /app/manual_auth.py" ]
    stdin_open: true
    tty: true
    init: true
    environment:
      XDG_RUNTIME_DIR: /tmp
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      RUN_HEADLESS: false
      USER_E: ${USER_E}
      USER_P: ${USER_P}
    volumes:
      - ./browser-launch-params.json:/app/browser-launch-params.json:ro
      - ./manual_auth.py:/app/manual_auth.py:ro
      - ./browser-local-storage/:/app/browser-local-storage
      - ./browser-downloads/:/app/browser-downloads
    devices:
      - /dev/dri:/dev/dri
    profiles:
      - "manual"

networks:
  secure_net:
    external: true