services:
  backup:
    restart: always
    build:
      context: ..
      dockerfile: backup-server/Dockerfile
    tty: true
    volumes:
      - ./.auth_encoded:/app/.auth_encoded
      - ./downloads:/app/downloads
      - ./photos:/app/photos
    networks:
      - secure_net
    environment:
      BROWSER_SERVER_URL: ws://proxy:8080
      ENCODED_PASS: ${ENCODED_PASS}
      GOOGLE_LANG: RU

networks:
  secure_net:
    external: true
