services:
  backup:
    restart: always
    build:
      context: ..
      dockerfile: backup-server/Dockerfile
    tty: true
    volumes:
      - ./.auth_encoded:/app/.auth_encoded
      - ./.fp_settings:/app/.fp_settings
      - ./downloads:/app/downloads
      - ./photos:/app/photos
    environment:
      BROWSER_SERVER_URL: ${BROWSER_SERVER_URL:-ws://host.docker.internal:8082}
      ENCODED_PASS: ${ENCODED_PASS}
      GOOGLE_LANG: RU
